---
title: "hw3"
author: "David Segan"
date: "4/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# import libraries
library(tidyverse)
library(here)
library(devtools)
library(purrr)

```

```{r}
# call function that calculates the yield anomaly for almonds
source("almond_anomaly.R")
almond_anomaly

```

```{r}
# Instructions for sensitivity analysis:
# Vary 0.0043P^2 parameter using rnorm() function, where n=500. Mean = parameter, stdv = 0.001

# read in data
climate_df <- read.delim(here('clim.txt'), sep = " ")

# run the model
almond_anomaly(climate_df, coef_t1=-0.015, coef_t2=0.0043, coef_p1=-0.07, coef_p2=0.0043, intercept=0.28)

# results
yield_anomaly = almond_anomaly(climate_df, coef_t1=-0.015, coef_t2=0.0043, coef_p1=-0.07, coef_p2=0.0043, intercept=0.28)

# sensitivity analysis 

# normal distribution of parameter 2
input_coef_t2 = rnorm(mean=0.0043, sd = 0.001, n=500)

# apply 500 different par 2 values to function 
# result is 500 lists. each has two columns (year and yield anomalies) and 22 rows
yield_anomaly_sens = input_coef_t2 %>% map(~almond_anomaly(climate_df, coef_t1=-0.015, coef_t2=.x, coef_p1=-0.07, coef_p2=0.0043, intercept=0.28))

head(yield_anomaly_sens)

#

# this is pretty messy - but we can extract a useful data structure,lets say we want # just the annual data (not the mean), and then reformat as a data frame with nice column names
tmp = map_df(yield_anomaly_sens,`[`, c("annual")) 
site2df = data.frame(year = tmp$annual$year, elect= tmp$annual$elect)
# now we could plot
ggplot(site2df, aes(year,elect, group=year ))+geom_boxplot()




```

